/*
 * SWARM
 * System of Wide-Applicable Robotics Modules
 *
 * @module Sensor/Proximity/Infrared
 */

#ifndef SENSOR_PROXIMITY_INFRARED_CONFIG_H
#define SENSOR_PROXIMITY_INFRARED_CONFIG_H

#define SENSOR_PROXIMITY_INFRARED_THRESHOLD  800

#define SENSOR_PROXIMITY_INFRARED_NORTH_EAST 7
#define SENSOR_PROXIMITY_INFRARED_EAST       4
#define SENSOR_PROXIMITY_INFRARED_SOUTH_EAST 3
#define SENSOR_PROXIMITY_INFRARED_SOUTH_WEST 2
#define SENSOR_PROXIMITY_INFRARED_WEST       1
#define SENSOR_PROXIMITY_INFRARED_NORTH_WEST 0

#endif
